apiVersion: v1
kind: PersistentVolume
metadata:
  name:  wordpress-persistent-storage-lab
  labels:
    app: wordpress
    tier: frontend
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.39.63
    # Exported path of your NFS server
    path: "/html"
