apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage-lab
  labels:
    app: wordpress
    tier: mysql
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.39.63
    path: "/mysql"
