apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage-lab
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
